---
title: "Taller 3: Ejercicio {readr}, {tidyr} {dplyr}"
subtitle: "Minería de datos (DTSE1017)"
author: "Francisco Zambrano"
format:
  html:
    number-sections: true
    number-depth: 3
    smooth-scroll: true
    code-fold: show
    toc: true
    html-math-method: katex
    self-contained: true
execute: 
  cache: false
editor: visual
---

## Ejercicios {readr} y {tidyr}

1.  con los datos de `agromet` cree datos anidados por estación (station_id) considerando todas las variables climáticas.
2.  de la data anidada extraiga el primer valor de la variable humedad relativa de la estación que se encuetra en la posición 5.
3.  agregue la variable precipitación extraida de la columna anidada como una variable adicional
4.  aplane (desanide) la variable de precipitación anterior.
5.  Haga explicitos los valores NA implicitos de precipitación. Comparé la cantidad de observaciones con la data original.
6.  relicé el rellenado de los valores NA de precipitación horaria tomando el valor anterior.

## Ejercicios {dplyr} (parte 1)

1.  Filtrar con los datos de agromet para las estaciones asignadas (ej., Pablo, Jessica y Lucas)\
2.  Filtrar los datos para los meses de Mayo a Julio en las estaciones asignadas.\
3.  Tome una muestra de 1000 filas de forma aleatoria sin reemplazo.\
4.  Para cada estación seleccione los valores máximos de precipitación horaria.\
5. Seleccione las columnas que tienen temperatura, además de station_id y fecha_hora.
6.  Seleccione las columnas que tienen valores no numéricos.
7. Cree una función y usela con la función `where` y `select`, luego eleccione las columnas que tienen valores menores a 0

## Ejercicios {dplyr} (parte 2)

1.  Agrupe los datos de las climáticos de agromet por estación (`group_by`)
2.  Haga un sumarizado de promedio mensual de las variables de temperatura para cada estación (`group_by`, `summarize` y `across`).
3.  Renombre y reordene las variables como `temp_prom`, `temp_max` y `Temp_min` (`rename_with` y \`relocate\`\`)
4.  Cree las columnas `var_temp` y `temp`, en formato largo que contenga las variables de `temp_prom`, `temp_max` y `Temp_min` y sus valores. (`pivot_longer`)
5.  Ordene los datos anteriores de mayor a menor.
6.  Vuelva a formato ancho los datos del punto anterior.
7.  Caclule cuantos datos no faltantes (!is.na) tiene cada estacion para cada una de las variables.

## Ejercicios {dplyr} {parte 3}

1.  Con los datos de agromet, calcule el promedio de temperatura (media, máxima, mínima) por día y estación. Utilice `summarize` y `across`.
2.  Para cada estacion calcule el valor de la mediana.
3.  Filtre las estaciones cuyo valor de temperatura promedio es mayor que la temperatura mediana.
4.  Verifique que los nombres de la estaciones son únicos (`distinct`).
5.  Extraiga la columna del nombre de la estaciones.
6.  Una el data.frame de los valores promedios de temperatura diario por estación con el data.frame de la metadata de las estaciones de agromet.
7.  Cree un data.frame con datos anidados con los valores de promedios de temperatura diario, por estación.
